# Generated by Django 4.2.8 on 2024-12-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Old_One', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('image', models.ImageField(upload_to='clients/')),
                ('description', models.TextField()),
            ],
        ),
    ]
