# Generated by Django 4.2.8 on 2024-12-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Old_One', '0004_managementteam_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5)),
                ('image', models.ImageField(upload_to='Management/')),
                ('description', models.TextField()),
                ('additional_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='team_member',
        ),
        migrations.DeleteModel(
            name='ManagementTeam',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
