# Generated by Django 4.2.8 on 2024-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Old_One', '0005_timelineitem_remove_milestone_team_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='left_placeholder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='right_placeholder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='timeline_images/'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10),
        ),
    ]
