# Generated by Django 4.2.8 on 2024-12-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Old_One', '0007_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
